### PR TITLE
feat: improve spacing project sheet cards + fix update card border

### LINKED ISSUE #80: Project sheet: improve spacing between update cards

### LINKED ISSUE #81: Broken styles on Updates card on Projects card on Projects page
Red border and no bottom border radius.

### PR DESCRIPTION
**Pull request by andyesp**
Closes #80 
Closes #81

### CODE REVIEW

File: src/components/Projects/ProjectSheetStatusPill.tsx [hunk 1]
```diff
@@ -27,6 +28,8 @@ export default function ProjectSheetStatusPill({ project, hero = false }: Props)
   const { status, created_at, updated_at } = project
   const t = useFormatMessage()
 
+  console.log('p', project)
```
Comment (1emu) [inline src/components/Projects/ProjectSheetStatusPill.tsx:31]: this can fly away

**Review by 1emu — APPROVED** [review]
